"""empty message

Revision ID: 7af0e2eba22c
Revises: 
Create Date: 2017-08-06 23:27:32.875651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7af0e2eba22c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_logins_username'), 'logins', ['username'], unique=False)
    op.drop_index('ix_logins_email', table_name='logins')
    op.drop_column('logins', 'email')
    op.add_column('users', sa.Column('friends', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'friends')
    op.add_column('logins', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_logins_email', 'logins', ['email'], unique=False)
    op.drop_index(op.f('ix_logins_username'), table_name='logins')
    op.drop_column('logins', 'username')
    # ### end Alembic commands ###
